apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: demoproject
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: demoproject
        version: v1
    spec:
      containers:
      - name: demoproject
        image: pushkale/demoproject:1
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent #Always
        ports:
        - containerPort: 8080