apiVersion: v1
kind: ReplicationController
metadata:
  name: demoproject4
spec:
  replicas: 3
  selector:
    app: demoproject4
  template:
    metadata:
      name: demoproject4
      labels:
        app: demoproject4
    spec:
      containers:
      - name: demoproject3
        image: registry.ng.bluemix.net/demoproject_ns/demoproject
        ports:
        - containerPort: 80